"""The wire vocabulary: opcode and notice names, result codes, and which ACK
answers which request.
"""
import os
import janwire                                                  # noqa: E402

# Generated by `python work/ps2/janproto.py --tsv` from the name table at
# 0x003e43d0. Regenerate rather than editing: index IS the wire opcode.
#: MjISAYGALLEY (1) is DEAD in this client build: sending it needs chat flag
#: bit 2 and showing it bit 8, and the table screen initialises the widget
#: with flags 5 for players and spectators alike (chat.c:661-665, 707;
#: lobby.c:312). A spectator's line leaves as plain MjISAY on the table
#: channel; `_relay_chat` fans it out.
OPCODES = (
    'MjISAY', 'MjISAYGALLEY', 'MjPLAYREQ', 'MjPLAYCANCEL', 'MjRESERVEACK',
    'MjMEMBERLISTREQ', 'MjGALLEYREQ', 'MjGALLEYLEAVEREQ', 'MjMEMBERBANISH', 'MjCHMASTER',
    'MjTBLCONFSTART', 'MjGAMESTART', 'MjMASTERCMDACK', 'MjTBLCONFALL', 'MjNOTICEMEMBER',
    'MjNOTICEBANISH', 'MjNOTICECALL', 'MjNOTICECALLACK', 'MjNOTICEGAMESTART',
    'MjNOTICETIMEUPWARNING', 'MjNOTICEGAMESETUP', 'MjNOTICESERVERQUIT', 'MjLEAVEROOM',
    'MjENTERROOM', 'MjLEAVECONTENTS', 'MjENTERCONTENTS', 'MjMOVEACK', 'MjTGMPING',
    'MjTGMPONG', 'MjLEAVEGAME', 'MjLEAVEGAMEACK', 'MjENTERGAME', 'MjENTERGAMEACK',
    'MjREADY', 'MjHAIPAI', 'MjHAIPAIACK', 'MjTSUMO', 'MjSUTE', 'MjNAKI', 'MjNAKIACK',
    'MjYAKUDISP', 'MjYAKUDISPACK', 'MjSEISAN', 'MjSEISANACK', 'MjGAMEEND', 'MjBYE',
    'MjALLDATA', 'MjALLDATAACK', 'MjGALLEYACK', 'MjSASHIUMASTART', 'MjSASHIUMAREQUEST',
    'MjSASHIUMASELECT', 'MjSASHIUMAARGEE', 'MjSASHIUMARESULT', 'MjGAMERESULT',
    'MjGAMERESULTACK', 'MjGAMERESULTHALF1', 'MjGAMERESULTHALF1ACK', 'MjGAMERESULTHALF2',
    'MjGAMERESULTHALF2ACK', 'MjMEMBERLEAVE', 'MjMEMBERLEAVEANSER', 'MjHAIPAIDEBUG',
    'MjHAIPAIDEBUGACK', 'MjGETLNDV', 'MjGETLNDVACK', 'MjREADYSTATUS', 'MjCHECKSAVEDATA',
    'MjCHECKSAVEDATAACK', 'MjCHATMEMBERADD', 'MjCHATMEMBERDEL', 'MjCHATMEMBERACK',
    # 0x48 -- NOT in the client's name table (it ends at 71), but a real
    # opcode: `sqFileAccess__INFO_00372ea0` sends it right after
    # MjCHATMEMBERADD with a 16-byte "INFO" name at +0x18 and "%s has
    # entered." at +0x28, and the receive loop `sqFileAccess__003730d0`
    # returns 3 for it (a system line). Named here so the log stops calling
    # it "Mj Non Defind...(72)".
    'MjCHATINFO',
    # 73..100 exist only in the 2004 build (20040727_2), whose table at
    # 0x00485750 has 112 names. It also calls 72 MjCHATINFOMSG and reuses 15
    # as MjNOTICECANCEL. Only 92/93 are used on the wire.
    'UdCONNECT', 'UdCONNECTACK', 'UdDISCONNECT', 'UdDISCONNECTACK', 'UdGETSAVEDATA',
    'UdGETSAVEDATASTATUS', 'UdGETSAVEDATAACK', 'UdSETSAVEDATA', 'UdSETSAVEDATASTATUS',
    'UdSETSAVEDATAACK', 'UdSAVEDATAPACKET', 'UdDETECT', 'UdDETECTACK', 'UdPLAYERLIST',
    'UdPLAYERLISTACK', 'EmENTRYEVENT', 'EmENTRYEVENTACK', 'EmEVENTOPENCLOSE',
    'EmREPORTRANKINGID', 'EmISEVENT', 'EmISEVENTACK', 'CmNOTICEMSGOPEN',
    'CmNOTICEMSGCLOSE', 'CmNOTICEJANHOLOWKICK', 'EmEVENTPARTICIPANTADD',
    'EmEVENTPARTICIPANTADDACK', 'EmGETEVENTPARTICIPANT', 'EmGETEVENTPARTICIPANTACK',
)

# The seven TGM_NOTICE_* names at 0x00417040. rec[0x17] routes into queues 2..8
# via the table at 0x003e4520, so it is a subsystem selector, not a free field.
NOTICES = (
    'TGM_NOTICE_MEMBER_LIST', 'TGM_NOTICE_BANISH', 'TGM_NOTICE_TABLE_CALL',
    'TGM_NOTICE_GAME_START', 'TGM_NOTICE_TIME_UP_WARNING', 'TGM_NOTICE_GAME_SETUP',
    'TGM_NOTICE_SERVER_QUIT',
)

# Table-reservation result codes, read off the if/else ladder in
# wrsCpTableReserveCheck() at 0x002cabf0: `if (code == N) log(<name>)`, N = 1..11.
# The client takes the code from rec[0x18] of an MjRESERVEACK.
RESERVE_RESULTS = {
    1: 'Reserve',            # seated
    2: 'ReserveMaster',      # seated, and you are the table master
    3: 'ReserveDuplicate',
    4: 'ReserveDuplicate2',
    5: 'ReserveCancel',
    6: 'ReserveCancelError',
    7: 'ReserveReject',
    8: 'ReserveTimeOut',
    9: 'ReservePassWordError',
    10: 'ReserveLimit',
    11: 'ReservePOLproDataFlush',
}

# What the client actually requires of an MjRESERVEACK, from 0x002caba4:
#
#     0x002c9d80(5, buf)                 <- reservation traffic is QUEUE 5
#     if (buf[0x12] != 4)        return   -- opcode must be MjRESERVEACK
#     if (buf[0x13] != (tag & 0x0f)) return
#     result = buf[0x18];  extra = buf[0x19]
#
# So rec[0x13] is a CORRELATION TAG the client keeps in a global and compares
# against; a reply carrying the wrong one is silently dropped. That is what the
# unexplained "f13" field is, protocol-wide -- MjSUTE loads it from a global too
# (0x00285bec).
#
# WARNING: IT IS NOT A NIBBLE, AND MASKING IT TO ONE HANGS THE CLIENT. Corrected
# 2026-08-17 after a live hang on the rules screen. The two gates use DIFFERENT
# globals and DIFFERENT shapes:
#
#   objstrings__MjTgmTblReserve_002cab50   opcode 4   buf[0x13] == DAT_00449048 & 0xf
#   malloc__MjTgmTmCmdSuccess_002c5400     opcode 12  buf[0x13] == DAT_00449058 & 0xf | 0x20
#                                                                                  ^^^^^^
# and all four master-command senders (malloc.c) build theirs as
# `bStack_1ed = ++DAT_00449058 & 0xf | 0x20`. So in BOTH families the byte the
# client sends is the byte it wants back, and the only correct rule is to
# **echo rec[0x13] VERBATIM**.
#
# Masking to & 0x0f is what we did, and it worked for reserve purely by accident
# -- that tag has no high bits to lose. MjTBLCONFALL arrived with f13=0x21, we
# answered 0x01, `wrsCpMasterCmdCheck` compared it against 0x21 and returned 0 =
# still pending, and the table screen polled until its own 120000-tick timeout.
# Live evidence: MjPLAYREQ f13=1 -> ack f13=1 advanced; MjTBLCONFALL f13=33 ->
# ack f13=1 did not.
RESERVE_QUEUE = 5

# THE ROUTING RULE, read off 0x002c9d80 in full on 2026-08-12 after a live client
# bounced our reply straight back at us. It is simpler than every previous note
# here, and both of those notes were wrong:
#
#   0x002c9d80(sub, buf):
#       loop: rec = getRecord(scratch, 1)          <- ALWAYS FIFO 1, the raw inbound
#             if !rec: break
#             put(scratch, TABLE[rec[0x17]], len)  <- bucket it by its OWN sub-code
#       return getRecord(buf, TABLE[sub])          <- then take one from MY bucket
#
# The table is applied to BOTH sides, so it cancels. The rule for a server is
# therefore just: **rec[0x17] must equal the sub-code the waiting gate passes.**
# There is no queue arithmetic to do at all.
#
#   gate                          waits with        so the ACK needs rec[0x17] =
#   wrsCpTableReserveCheck() etc  drain(5)          5
#   the MjGETLNDV poll            drain(0)          0
#
# What this corrects: the older note said "rec[0x17] INDEXES the table and the
# entry is the queue, so to land in queue 5 the sub-code is 3". The indexing part
# is right, but `a0` is NOT a queue -- it is a sub-code that gets indexed the same
# way. Deriving the sub from a queue produced sub=3 for the four ACKs (never live-
# tested) and, when I echoed the request's 5 for MjGETLNDV, sub=7 -- and TABLE[7]
# is 0, which is the OUTBOUND FIFO. The client obligingly serialised our own ACK
# and sent it back to us, which is exactly what the log showed.
SUB_TO_QUEUE = (2, 3, 4, 5, 6, 7, 8, 0)     # kept: it is the real table, and the
                                            # bucket a record lands in is still
                                            # TABLE[sub]. It just is not something
                                            # a server ever needs to invert.


def queue_for_sub(sub):
    """The FIFO a record with this rec[0x17] gets bucketed into. Diagnostics only
    -- a server picks `sub` to match a gate, never a queue."""
    return SUB_TO_QUEUE[sub] if 0 <= sub < len(SUB_TO_QUEUE) else -1


MjPLAYREQ, MjPLAYCANCEL, MjRESERVEACK = 2, 3, 4
MjGALLEYREQ, MjGALLEYLEAVEREQ = 6, 7
MjMEMBERBANISH, MjCHMASTER, MjTBLCONFSTART = 8, 9, 10
MjGAMESTART, MjMASTERCMDACK, MjTBLCONFALL = 11, 12, 13
MjNOTICETIMEUPWARNING, MjNOTICESERVERQUIT = 19, 21
MjLEAVEROOM, MjLEAVECONTENTS = 22, 24
MjENTERROOM = 23                    # client->server after a RESERVE; no reply drained
MjLEAVEGAME, MjLEAVEGAMEACK, MjENTERGAME, MjENTERGAMEACK = 29, 30, 31, 32
MjCHATMEMBERADD, MjCHATMEMBERDEL, MjCHATMEMBERACK, MjCHATINFO = 69, 70, 71, 0x48

#: The four builders that bump the RESERVE tag counter `DAT_00449048`
#: (objstrings.c:2555/2604/2806/2852). A kick is answered against THAT
#: counter (see `_kick`), so its latest value is remembered per seat.
RESERVE_TAG_OPCODES = (MjPLAYREQ, MjPLAYCANCEL, MjGALLEYREQ, MjGALLEYLEAVEREQ)

#: MjPLAYREQ +0x42 (u16): the player's VoiceCharaNum -- `lobbysub__002b9620`
#: copies option word[7] (voicesel.c "data.VoiceCharaNum") into the lobby
#: object's +0xb6, and `objstrings__002ca990` writes that as `uStack_1be`,
#: i.e. +0x42 of the 0x108-byte reserve record. It is the voice bank
#: `b/g/MJSTableInfoSub` +0x218 must serve back for the seat (lobby.c:138).
#: MjPLAYREQ +0x40, u16 LE -- the player's PlayOnline HANDLE-ICON index,
#: beside the voice at +0x42. The 2004 build reads a face per seat out of
#: `b/g/MJSTableInfoSub` and loads `hnf%03d.png` (index >> 3), cell
#: index & 7, from the Viewer's icon download folder. The client builds
#: the record at 0x003935e0 from its identity block: block+0x14 lands
#: here and block+0x16 at the voice, which is what pins the pair.
PLAYREQ_FACE_OFF = 0x40
PLAYREQ_VOICE_OFF = 0x42

#: MjMEMBERBANISH +0x28 (u64): the TARGET's PolID -- `malloc__002c4fb0`'s
#: third argument, `*(u64*)(ctx+0xa8)` in lmenu.c:1474 / the row's id in
#: TableMemberBanish.c:179. No name rides the request.
BANISH_TARGET_OFF = 0x28

RESERVE_RESULT = int(os.environ.get("POL_JAN_RESERVE_RESULT", "2"))   # 2 = Master
TMCMD_RESULT = int(os.environ.get("POL_JAN_TMCMD_RESULT", "1"))      # 1 = Success

# The MjTgmTmCmd* result family, from the identical ladders in
# wrsCpEnterGameCheck() 0x002cb218, wrsCpLeaveGameCheck() 0x002cb358 and
# wrsCpMasterCmdCheck() 0x002c5480. Same four codes, same byte, three functions.
TMCMD_RESULTS = {1: 'Success', 2: 'Failed', 3: 'NoAuthority', 4: 'POLproDataFlush'}

# Every ACK contract read so far, and they are strikingly uniform: all arrive on
# QUEUE 5, all carry their result in rec[0x18], and they differ only in the
# opcode and whether the correlation nibble is checked.
#
#   check function            queue  opcode                nibble  results
#   wrsCpTableReserveCheck()    5    4  MjRESERVEACK        yes     RESERVE_RESULTS
#   wrsCpMasterCmdCheck()       5   12  MjMASTERCMDACK      yes     TMCMD_RESULTS
#   wrsCpLeaveGameCheck()       5   30  MjLEAVEGAMEACK      no      TMCMD_RESULTS
#   wrsCpEnterGameCheck()       5   32  MjENTERGAMEACK      no      TMCMD_RESULTS
#
# We echo the nibble unconditionally: the two that check it require it, and the
# two that do not are indifferent, so there is no case where echoing is wrong.
ACK_FOR = {
    MjPLAYREQ: MjRESERVEACK,
    MjPLAYCANCEL: MjRESERVEACK,
    # WARNING: A KICK WAITS ON THE RESERVE CHECK, NOT THE MASTER-COMMAND ONE
    # (2026-09-04, audit finding 14). TableMemberBanish.c:152-153 and
    # lmenu.c:1473 both poll `objstrings__MjTgmTblReserve_002cab50`, which
    # accepts only opcode 4 with +0x13 == `DAT_00449048 & 0xf` -- the RESERVE
    # counter. Answering MjMASTERCMDACK left the master on the "Removing
    # them from the table" spinner for 120000 ticks. The result byte's value
    # is never looked at (`!= 0` is the whole test). See `_kick`.
    MjMEMBERBANISH: MjRESERVEACK,
    MjCHMASTER: MjMASTERCMDACK,
    # MjGALLEYREQ/MjGALLEYLEAVEREQ wait on the same reserve check, with the
    # codes in `GALLEY_REFUSED` / `GALLEY_LEFT`.
    MjGALLEYREQ: MjRESERVEACK,
    MjGALLEYLEAVEREQ: MjRESERVEACK,
    MjTBLCONFSTART: MjMASTERCMDACK,
    # MjTBLCONFALL (13) -- ADDED 2026-08-16 from a LIVE wall, and it is the same
    # grade of inference as MjTBLCONFSTART above, not a measurement. Pressing OK
    # on the rules dialog sends opcode 13 (len 112, seq 0x21, sub 0x05) and the
    # log said `no handler`, so the table screen stops there. It is a master-only
    # command in the same 0-13 group as TBLCONFSTART, whose ACK is measured, so
    # MjMASTERCMDACK is the candidate. If the client ignores this reply, that is
    # DATA -- the nibble gate in wrsCpMasterCmdCheck() would drop a wrong-opcode
    # ACK silently, so a continued stall means the pairing is wrong, not the
    # framing.
    MjTBLCONFALL: MjMASTERCMDACK,
    MjGAMESTART: MjMASTERCMDACK,
    MjLEAVEGAME: MjLEAVEGAMEACK,
    MjENTERGAME: MjENTERGAMEACK,
}

# The sub-code the four gates wait on: every one of them calls 0x002c9d80(5, buf),
# so their ACKs must carry rec[0x17] = 5. (This was 3 until 2026-08-12, derived
# from the mistaken "sub indexes to a queue, wait on queue 5" reading. No live
# client had ever exercised these four, so the error was never visible.)
ACK_SUB = 5


def opname(op):
    return OPCODES[op] if 0 <= op < len(OPCODES) else "Mj Non Defind...(%d)" % op


def ack_for(req, result=None, extra=0):
    """Build the ACK the client's own gate will accept for `req`, or None.

    Every gate read so far wants the same four things: the right opcode, arrival
    on queue 5, the result code in rec[0x18], and (for two of them) rec[0x13]
    equal to the correlation tag the client is holding -- echoed VERBATIM,
    never masked (the master-cmd family carries 0x20 in it; see the note above).
    `extra` (rec[0x19]) is stored by the client but its meaning is not yet read,
    so it defaults to 0 rather than to a guess.

    MEASURED: the field layout, the queue, the opcode and the result ladders.
    INFERENCE: the request->ACK pairing. It is solid for 31->32 and 29->30
    (adjacent opcodes, matching names) and weaker for the master commands and
    MjPLAYREQ->MjRESERVEACK, where several requests plausibly share one ACK.
    A live client disagreeing is data, not a bug to paper over.
    """
    h = janwire.unpack(req)
    ack = ACK_FOR.get(h["opcode"])
    if ack is None:
        return None
    if result is None:
        result = RESERVE_RESULT if ack == MjRESERVEACK else TMCMD_RESULT
    rec = bytearray(janwire.pack(
        opcode=ack,
        f13=h["f13"],                           # the correlation tag, echoed VERBATIM
        src=janwire.DST_SERVER & 0xFF,
        dst=janwire.DST_REPLY & 0xFF,
        sub=ACK_SUB,                            # = the sub-code the gate drains on
        id8=h["payload"],
    ))
    rec[0x18] = result & 0xFF
    rec[0x19] = extra & 0xFF
    return bytes(rec)


def result_name(ack_opcode, code):
    table = RESERVE_RESULTS if ack_opcode == MjRESERVEACK else TMCMD_RESULTS
    return table.get(code, "?")
